version: "3.7"

services:
  request-multi:
    image: request_multi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nats

  nats:
    image: nats:2.1-alpine
    restart: always
    command:
      - "--debug"
      - "--trace"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--port"
      - "4222"
      - "--http_port"
      - "8222"
    ports:
      - "8222:8222"
      - "4222:4222"
